### ISSUE TITLE
Small bugs in SimpleRegressionResults

### ISSUE THREAD

**Issue by qmac** [nistats/nistats#150]
(1) https://github.com/nistats/nistats/blob/master/nistats/regression.py#L366
`predicted` should be a method call instead of an instance variable reference
```
Traceback (most recent call last):
  File "nistats_model_fitting.py", line 22, in compute_rsquared
    print(model.results_[0][0.0].resid(Y))
  File "/.../nistats/nistats/regression.py", line 366, in resid
    return Y - self.predicted
TypeError: unsupported operand type(s) for -: 'float' and 'method'
```
(2) https://github.com/nistats/nistats/blob/master/nistats/regression.py#L392
`model` is not defined in `SimpleRegressionResults`. It is defined in the parent class `LikelihoodModelResults` but the initializer for the parent is never called.
```
Traceback (most recent call last):
  File "nistats_model_fitting.py", line 22, in compute_rsquared
    print(model.results_[0][0.0].predicted())
  File "/.../nistats/nistats/regression.py", line 392, in predicted
    X = self.model.design
AttributeError: 'SimpleRegressionResults' object has no attribute 'model'
```

**Comment by bthirion** [comment]
Thx for pointing these issues. These classes were inherited from past projects and are actually not used correctly. 
Please issue a PR if you wish to fix this.
In the longer term, I'd like to simplify that part of the code base (having less generic objects).

**Comment by bthirion** [comment]
Actually, all these excellent why we should be careful with inheritance and avoid over-designing the code.

**Comment by Gilles86** [comment]
I think I fixed it. Please give me some feedback.

https://github.com/Gilles86/nistats/tree/fix_firstlevel

**Comment by KamalakerDadi** [comment]
@Gilles86 I think the best way is to open a PR saying that it fixes this issue. In that way you would hopefully get feedback. 
Thanks

**Comment by bthirion** [comment]
Indeed. let us jknow if you need help or explanations.
