### ISSUE TITLE
make html failing locally on master branch 

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#249]
Anyone else seeing this?
@bthirion 

Traceback:

```
Unexpected failing examples:
/home/kshitij/workspace/nistats-org/nistats-repo/kchawla-pi/nistats/examples/02_first_level_models/plot_localizer_analysis.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/kshitij/workspace/nistats-org/nistats-repo/kchawla-pi/nistats/doc/sphinxext/sphinx_gallery/gen_rst.py", line 450, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 8, in <module>
  File "/home/kshitij/anaconda3/envs/nistats-py36/lib/python3.6/site-packages/pandas/core/generic.py", line 4389, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/kshitij/anaconda3/envs/nistats-py36/lib/python3.6/site-packages/pandas/core/generic.py", line 646, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/kshitij/anaconda3/envs/nistats-py36/lib/python3.6/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements

home/kshitij/workspace/nistats-org/nistats-repo/kchawla-pi/nistats/examples/02_first_level_models/plot_localizer_surface_analysis.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/kshitij/workspace/nistats-org/nistats-repo/kchawla-pi/nistats/doc/sphinxext/sphinx_gallery/gen_rst.py", line 450, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 9, in <module>
  File "/home/kshitij/anaconda3/envs/nistats-py36/lib/python3.6/site-packages/pandas/core/generic.py", line 4389, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/kshitij/anaconda3/envs/nistats-py36/lib/python3.6/site-packages/pandas/core/generic.py", line 646, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/kshitij/anaconda3/envs/nistats-py36/lib/python3.6/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements
```

**Comment by bthirion** [comment]
I've never seen that. Did you see that occurring on Travis ?

**Comment by kchawla-pi** [comment]
No, only while using `make html`. 
I did a rebuild on CircleCI and it is green there. Not sure what the problem is on my system. I might have to push just to get check CircleCI tests running properly until i fix this, which is not today.

**Comment by bthirion** [comment]
If you haven't, you can do a  make clean and rebuild.

**Comment by kchawla-pi** [comment]
I have. No dice.

**Comment by kchawla-pi** [comment]
Figured it out.
For the tutorial, I recommend using pandas.read_table() for reading .tsv files as it has all the correct default args, unlike read_csv()
